### ISSUE TITLE
Gestão dos campos para parlamentares

### ISSUE THREAD

**Issue by jpmehl** [redelivre/BotaPressao#13]
A partir do mapeamento de votos/discurso/ocorrências judiciais, demandamos a seguinte estrutura de dados: 
1. Nome;
2. Partido;
3. Estado;
4. Gênero;
5. Declaração de voto;
6. Ocorrências Judiciais;
7. Número de ocorrências;
8. Tipo de voto; 
9. Bancada que compões;
10. Profissão;
11. Foto;
12. E-mail;
13. Telefone;
14. Facebook;
15. Twitter
16. Whatsapp

**Comment by cabelotaina** [comment]
Segue a lista do que já foi resolvido, falta apenas as fotos.
1. Nome; ok 
2. Partido; ok
3. Estado; ok
4. Gênero; ok
5. Declaração de voto; ok
6. Ocorrências Judiciais; ok
7. Número de ocorrências; ok
8. Tipo de voto; ok
9. Bancada que compões; ok
10. Profissão; ok
11. Foto; ok
12. E-mail; ok
13. Telefone; ok
14. Facebook; ok
15. Twitter; ok
16. Whatsapp; ok
